unicode to ascii
EnCiv/enciv-home pull request #27
Opened 2024-06-22 20:50 UTC by baraahmad

2024-06-24 05:41 UTC, ddfridley requested changes
It works great. I appreciate that the unicode character got mapped into something.
Please remove the unrelated comment.
Also, there was no readme with contributing info so you wouldn't know this but please add a comment to the top of the file, linking to github issue you are working on.
And here's the contributing info: 
[Contribute](https://github.com/EnCiv/.github/wiki/Contributing)
[React Coding and Style Guidlines](https://github.com/EnCiv/.github/wiki/React-Coding-and-Style-Guidelines)

Thanks!

2024-06-24 05:41 UTC, ddfridley commented on app/web-components/article.js
> +// import { ConvertUnicode } from '../components/convert-unicode'
please remove this comment since it's not relevant going forward.

2024-06-24 15:45 UTC, baraahmad commented
I removed the unnecessary comment you mentioned and included a link to the
github issue as a comment at the top of the article component.


On Mon, 24 Jun 2024 at 01:41, David ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> It works great. I appreciate that the unicode character got mapped into
> something.
> Please remove the unrelated comment.
> Also, there was no readme with contributing info so you wouldn't know this
> but please add a comment to the top of the file, linking to github issue
> you are working on.
> And here's the contributing info:
> Contribute <https://github.com/EnCiv/.github/wiki/Contributing>
> React Coding and Style Guidlines
> <https://github.com/EnCiv/.github/wiki/React-Coding-and-Style-Guidelines>
>
> Thanks!
> ------------------------------
>
> In app/web-components/article.js
> <https://github.com/EnCiv/enciv-home/pull/27#discussion_r1650372544>:
>
> > @@ -1,12 +1,21 @@
>  import React from 'react'
>  import ArticleBlock from '../components/article-block'
>  import { BrevoHelmet } from '../components/brevo-join'
> +import { Helmet } from 'react-helmet'
> +// import { ConvertUnicode } from '../components/convert-unicode'
>
> please remove this comment since it's not relevant going forward.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EnCiv/enciv-home/pull/27#pullrequestreview-2134691896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMVNGMS4VNFE3TFL2YSTFVDZI6WR3AVCNFSM6AAAAABJXW56MKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMZUGY4TCOBZGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-27 22:23 UTC, ddfridley approved these changes
Looks Great!

2024-06-27 22:23 UTC, merged